version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 8
    groups:
      dev-dependencies:
        dependency-type: development
        patterns:
          - "@types/*"
          - "eslint*"
          - "typescript*"
          - "vitest"
          - "prettier"
          - "globals"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
