export const APP_BACKGROUND_COLOR = '#0A0E14'

export const MIN_WINDOW_WIDTH = 1280
export const MIN_WINDOW_HEIGHT = 800

export const DEFAULT_WINDOW_WIDTH = 1400
export const DEFAULT_WINDOW_HEIGHT = 900
